version: "3"

services:

  asp-rubber-user-service:
    build: .
    ports:
      - 5005:5005
      - 8000:8000
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - ".:/opt/asp-user-service"
      - "/opt/asp-user-service/target"
      - "/opt/asp-user-service/project/target"
    environment:
      MONGO_HOST: "mongo-database"
      MONGO_PORT: "27017"
      MONGO_USERNAME: "asp-rubber"
      MONGO_PASSWORD: "secret-password"

  mongo-database:
    image: bitnami/mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: "asp-rubber-user-service"
      MONGODB_USERNAME: "asp-rubber"
      MONGODB_PASSWORD: "secret-password"